### ISSUE TITLE
compile errors

### ISSUE THREAD

**Issue by Alex-CodeLab** [commandus/clitox#2]
getting this error when trying to install

```
make[2]: Entering directory '/projects/clitox'
g++ -DHAVE_CONFIG_H -I.  -std=c++11 -O2 -I/usr/local/include   -g -O2 -MT clitox-clitox-config.o -MD -MP -MF .deps/clitox-clitox-config.Tpo -c -o clitox-clitox-config.o `test -f 'clitox-config.cpp' || echo './'`clitox-config.cpp
clitox-config.cpp: In member function ‘int ClitoxConfig::parseCmd(int, char**)’:
clitox-config.cpp:125:13: error: ‘struct Tox_Options’ has no member named ‘local_discovery_enabled’
  toxoptions.local_discovery_enabled = a_local_discovery_disabled->count == 0;
             ^
clitox-config.cpp:158:14: error: ‘struct Tox_Options’ has no member named ‘hole_punching_enabled’
   toxoptions.hole_punching_enabled = false;
              ^
clitox-config.cpp: In static member function ‘static void ClitoxConfig::defaultToxOptions(Tox_Options*)’:
clitox-config.cpp:215:10: error: ‘struct Tox_Options’ has no member named ‘local_discovery_enabled’
  retval->local_discovery_enabled = true;
          ^
clitox-config.cpp:222:10: error: ‘struct Tox_Options’ has no member named ‘hole_punching_enabled’
  retval->hole_punching_enabled = true;
          ^
clitox-config.cpp: In member function ‘void ClitoxConfig::getToxOptions(Tox_Options*)’:
clitox-config.cpp:232:10: error: ‘struct Tox_Options’ has no member named ‘local_discovery_enabled’
  retval->local_discovery_enabled = toxoptions.local_discovery_enabled;
          ^
clitox-config.cpp:232:47: error: ‘struct Tox_Options’ has no member named ‘local_discovery_enabled’
  retval->local_discovery_enabled = toxoptions.local_discovery_enabled;
                                               ^
clitox-config.cpp:239:10: error: ‘struct Tox_Options’ has no member named ‘hole_punching_enabled’
  retval->hole_punching_enabled = toxoptions.hole_punching_enabled;
          ^
clitox-config.cpp:239:45: error: ‘struct Tox_Options’ has no member named ‘hole_punching_enabled’
  retval->hole_punching_enabled = toxoptions.hole_punching_enabled;
                                             ^
Makefile:648: recipe for target 'clitox-clitox-config.o' failed
make[2]: *** [clitox-clitox-config.o] Error 1
make[2]: Leaving directory '/projects/clitox'
Makefile:904: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/projects/clitox'
Makefile:471: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by commandus** [comment]
Hi,

Looks like you have another version of tox client library installed, in my opinion first please update dependencies on tox https://github.com/TokTok/c-toxcore

Отправлено из Почта для Windows 10

От: Alex
Отправлено: 3 марта 2018 г. в 17:44
Кому: commandus/clitox
Копия: Subscribed
Тема: [commandus/clitox] compile errors (#2)

getting this error when trying to install
make[2]: Entering directory '/projects/clitox'
g++ -DHAVE_CONFIG_H -I.  -std=c++11 -O2 -I/usr/local/include   -g -O2 -MT clitox-clitox-config.o -MD -MP -MF .deps/clitox-clitox-config.Tpo -c -o clitox-clitox-config.o `test -f 'clitox-config.cpp' || echo './'`clitox-config.cpp
clitox-config.cpp: In member function ‘int ClitoxConfig::parseCmd(int, char**)’:
clitox-config.cpp:125:13: error: ‘struct Tox_Options’ has no member named ‘local_discovery_enabled’
  toxoptions.local_discovery_enabled = a_local_discovery_disabled->count == 0;
             ^
clitox-config.cpp:158:14: error: ‘struct Tox_Options’ has no member named ‘hole_punching_enabled’
   toxoptions.hole_punching_enabled = false;
              ^
clitox-config.cpp: In static member function ‘static void ClitoxConfig::defaultToxOptions(Tox_Options*)’:
clitox-config.cpp:215:10: error: ‘struct Tox_Options’ has no member named ‘local_discovery_enabled’
  retval->local_discovery_enabled = true;
          ^
clitox-config.cpp:222:10: error: ‘struct Tox_Options’ has no member named ‘hole_punching_enabled’
  retval->hole_punching_enabled = true;
          ^
clitox-config.cpp: In member function ‘void ClitoxConfig::getToxOptions(Tox_Options*)’:
clitox-config.cpp:232:10: error: ‘struct Tox_Options’ has no member named ‘local_discovery_enabled’
  retval->local_discovery_enabled = toxoptions.local_discovery_enabled;
          ^
clitox-config.cpp:232:47: error: ‘struct Tox_Options’ has no member named ‘local_discovery_enabled’
  retval->local_discovery_enabled = toxoptions.local_discovery_enabled;
                                               ^
clitox-config.cpp:239:10: error: ‘struct Tox_Options’ has no member named ‘hole_punching_enabled’
  retval->hole_punching_enabled = toxoptions.hole_punching_enabled;
          ^
clitox-config.cpp:239:45: error: ‘struct Tox_Options’ has no member named ‘hole_punching_enabled’
  retval->hole_punching_enabled = toxoptions.hole_punching_enabled;
                                             ^
Makefile:648: recipe for target 'clitox-clitox-config.o' failed
make[2]: *** [clitox-clitox-config.o] Error 1
make[2]: Leaving directory '/projects/clitox'
Makefile:904: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/projects/clitox'
Makefile:471: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Alex-CodeLab** [comment]
that tox client library does not compile either.
I'll try again in a year or so :)
